CREATE TABLE Ticket (
id INTEGER AUTO_INCREMENT NOT NULL,
filmName VARCHAR(255) NOT NULL ,
forNavn VARCHAR(255) NOT NULL,
etterNavn VARCHAR(255) NOT NULL,
count INTEGER NOT NULL,
email VARCHAR(255) NOT NULL,
telNummer VARCHAR(255) NOT NULL,
PRIMARY KEY(id)
);